### ISSUE TITLE
Input out of bounds in a model exported from onnx function

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnx-script#371]
Error:
```
Traceback (most recent call last):
  File "/home/titaiwang/onnx-script/bug_onnxscript.py", line 11, in <module>
    expected = onnx.shape_inference.infer_shapes(expected)
  File "/home/titaiwang/anaconda3/envs/pytorch-dev/lib/python3.9/site-packages/onnx/shape_inference.py", line 40, in infer_shapes
    inferred_model_str = C.infer_shapes(
RuntimeError: Input 1 is out of bounds.
```

Repro (modified from @justinchuby comment below)
```python
import onnxscript
from onnxscript import FLOAT, opset18 as op
from onnxscript.function_libs.torch_aten.ops.core import aten_amax
import onnx

@onnxscript.script()
def expected_model(x: FLOAT[2, 3, 4]):
    return aten_amax(x, op.Constant(value_int=0), keepdim=False)

proto = expected_model.to_model_proto()
with_shape = onnx.shape_inference.infer_shapes(proto)
onnx.checker.check_model(with_shape, full_check=True)
```

cc @gramalingam @justinchuby

**Comment by justinchuby** [comment]
The previous was a wrong call since dim is an input. The new function

```python
import onnxscript
from onnxscript import FLOAT, opset18 as op
from onnxscript.function_libs.torch_aten.ops.core import aten_amax
import onnx

@onnxscript.script()
def expected_model(x: FLOAT[2, 3, 4]):
    return aten_amax(x, op.Constant(value_int=0), keepdim=False)

proto = expected_model.to_model_proto()
with_shape = onnx.shape_inference.infer_shapes(proto)
onnx.checker.check_model(with_shape, full_check=True)
```

gets an error

```
Traceback (most recent call last):
  File "/home/justinchu/dev/onnx-script/testtest.py", line 12, in <module>
    onnx.checker.check_model(with_shape, full_check=True)
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/onnx/checker.py", line 117, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.
```

**Comment by justinchuby** [comment]
```
<
   ir_version: 8,
   opset_import: ["" : 18, "onnxscript.atenlib" : 1]
>
expected_model (float[2,3,4] x) => (float[] return_val) {
   tmp = Constant <value_int = 0> ()
   return_val = onnxscript.atenlib.aten_amax <keepdim = 0> (x, tmp)
}
<
  domain: "onnxscript.atenlib",
  opset_import: ["" : 18]
>
aten_amax <keepdim>(self, dim) => (return_val)
{
   return_val = ReduceMax <keepdims: int = @keepdim> (self, dim)
}
```

**Comment by gramalingam** [comment]
Hi,

I suspect this is due to this issue in ONNX: https://github.com/onnx/onnx/issues/3985 ... will test it more, and will work on the fix for that issue.

**Comment by gramalingam** [comment]
I think the above is correct. For example, changing `tmp = Constant <value_int = 0> ()` to `tmp = Constant <value_ints = [0]> ()` works. I would recommend this anyway, because it is better to keep the sequence of dimensions to be reduced as a 1D tensor anyway. (But there is a bug/incompleteness in ONNX as mentioned above that needs to be fixed too, but you can work around that as above for now ... alternatively, using just `0` instead of `tmp` may also work, assuming a 0D-tensor is ok.
