### ISSUE TITLE
ORT Flaky Segmentation Fault during model load

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnx-script#523]
[models.zip](https://github.com/microsoft/onnx-script/files/10973692/models.zip) contains two models, and they are only different on aten_sym_size, but results in differently. I tested them on the following code:

```python
import onnx
import onnxruntime as ort

model = onnx.load("model_works.onnx")
model = onnx.load("model_segfault.onnx")

model_string = model.SerializeToString()
print(model_string)
sess_options = ort.SessionOptions()
sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
sess = ort.InferenceSession(model_string, sess_options)
```

The one with Gather node flaky fails when InferenceSession is initialized, while the other one works fine. Even tried with ORT_DISABLE_ALL, but not worked either.

I am not sure if it's some corner case of local function that isn't handled well in ORT. I suspect this only happens when dynamic shape is involved, as I have seen it in other cases which I tried to enable dynamic shapes.

version:
ONNX 1.13.1
ONNXRUNTIME 1.14.1

cc @gramalingam @justinchuby @BowenBao

**Comment by gramalingam** [comment]
Hmmm ... it doesn't crash in my setup (a recent version I pulled and built from onnxruntime, not exactly same version as reported above, but still ...)

**Comment by titaiwangms** [comment]
@gramalingam Have you tried it multiple times? It crashes sometimes, not always. @jcwchen can confirm this.

**Comment by jcwchen** [comment]
Yes I have the same situation in my local (onnx 1.13.1 + onnxruntime 1.14.1). Sometimes `onnxruntime.InferenceSession` passed, throw an error or even crashed due to seg fault.

**Comment by gramalingam** [comment]
Oh, I see. Ok, will try.

**Comment by gramalingam** [comment]
Another question: does it happen even if we load directly from the file, instead of SerializeToString as above?

**Comment by jcwchen** [comment]
> Another question: does it happen even if we load directly from the file, instead of SerializeToString as above?

Both from my end.

**Comment by gramalingam** [comment]
But it never crashes with just onnx checker?

**Comment by jcwchen** [comment]
> But it never crashes with just onnx checker?

onnx.checker/onnx.shape_inference are always good.

**Comment by jcwchen** [comment]
More info:
Sometimes onnxruntime.InferenceSession will throw an error:
```
2 0 2 3 - 0 3 - 2 0   0 9 : 2 8 : 2 6 . 0 4 2 2 7 6 5   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 1 0 8   o n n x r u n t i m e : : M e r g e S h a p e I n f o ]   E r r o r   m e r g i n g   s h a p e   i n f o   f o r   o u t p u t .   ' 3 '   s o u r c e : { 2 8 3 2 1 1 2 1 1 2 5 2 8 }   t a r g e t : { 1 } .   F a l l i n g   b a c k   t o   l e n i e n t   m e r g e .
```

**Comment by justinchuby** [comment]
@titaiwangms looks like time to open it on ORT?

**Comment by titaiwangms** [comment]
I rebase with the latest PyTorch, and now failing on test_mnist, too. I really don't know what is causing this.

**Comment by BowenBao** [comment]
Crashing in CI too https://github.com/pytorch/pytorch/actions/runs/4601544636/jobs/8129704090?pr=98245

**Comment by BowenBao** [comment]
Very likely has something to do with shape inference with symbols. From my end that's what in common.

**Comment by titaiwangms** [comment]
> Very likely has something to do with shape inference with symbols. From my end that's what in common.

Yes, falling back to fake mode would avoid the crash.

**Comment by titaiwangms** [comment]
Had another test on test_mnist model. I compare two serialized model strings from Works/SegFault, and they appear to be exactly the same. If I save them before SerializetoString() into ONNX. And later use them to initialize InferenceSession, both of them are good. I think it might have something to do with the executing environment. at running time

**Comment by abock** [comment]
For me, both the "works" and "segfault" versions of the model crash on both of my machines:

* Ubuntu 22.04 / ORT 1.14.1 / Python 3.10.6
* macOS 13.2.1 / ORT 1.14.1 / Python 3.10.10

**Comment by abock** [comment]
However, on the Ubuntu machine at least, there is no crash on _either_ model when using the C API to simply create the session. This may hint the issue is in the pybind path of the codebase?

I built ORT with `./build.sh --cmake_generator Ninja --config Debug --build_shared_lib`.

### C Model Loader
```c
#include <stdio.h>
#include <onnxruntime/core/session/onnxruntime_c_api.h>

#define ORT_ABORT_ON_ERROR(expr)                                   \
    do {                                                           \
        OrtStatus* onnx_status = (expr);                           \
        if (onnx_status != NULL) {                                 \
            const char* msg = ort->GetErrorMessage(onnx_status); \
            fprintf(stderr, "%s\n", msg);                          \
            ort->ReleaseStatus(onnx_status);                       \
            abort();                                               \
        }                                                          \
    } while (0);

int main(int argc, const char* const* argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: ort_model_loader MODEL_PATH\n");
        return 1;
    }

    const OrtApi* ort =  OrtGetApiBase()->GetApi(ORT_API_VERSION);

    OrtEnv* env;
    ORT_ABORT_ON_ERROR(ort->CreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env));

    OrtSessionOptions* session_options;
    ORT_ABORT_ON_ERROR(ort->CreateSessionOptions(&session_options));
    ORT_ABORT_ON_ERROR(ort->SetSessionGraphOptimizationLevel(session_options, ORT_DISABLE_ALL));

    OrtSession* session;
    ORT_ABORT_ON_ERROR(ort->CreateSession(env, (ORTCHAR_T*)argv[1], session_options, &session));

    return 0;
}
```

### Makefile

```Makefile
# ORT was checked out at $(ORT_SRC_ROOT) below and built with:
#
# ./build.sh --cmake_generator Ninja --config Debug --build_shared_lib

ORT_SRC_ROOT := $(HOME)/src/onnxruntime/
ORT_INCLUDE_PATH := $(ORT_SRC_ROOT)include/
ORT_LIBRARY_PATH := $(ORT_SRC_ROOT)build/Linux/Debug/

CFLAGS := -I"$(ORT_INCLUDE_PATH)" -Wall -Werror
LDFLAGS := -L"$(ORT_LIBRARY_PATH)" -lonnxruntime

.PHONY: all
all: ort_model_loader

.PHONY: clean
clean:
    rm -f ort_model_loader

.PHONY: run
run: ort_model_loader
    LD_LIBRARY_PATH="$(ORT_LIBRARY_PATH)" ./$< ./model_works.onnx
    LD_LIBRARY_PATH="$(ORT_LIBRARY_PATH)" ./$< ./model_segfault.onnx

ort_model_loader: ort_model_loader.c
    $(CC) -o "$@" "$<" $(CFLAGS) $(LDFLAGS)
```

Further, under GDB when running the Python test case, the stack is the following:

```
Thread 1 "python3.10" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:370
370	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:370
#1  0x00007ffff713572e in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff7127b35 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffa46a0149 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#4  0x00007fffa4bf1b49 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#5  0x00007fffa4bfac2c in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#6  0x00007fffa4c01a2a in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#7  0x00007fffa4c05211 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#8  0x00007fffa4c6d482 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#9  0x00007fffa4cd8847 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#10 0x00007fffa4cda322 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#11 0x00007fffa4cdb3ee in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#12 0x00007fffa4cdb88b in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#13 0x00007fffa4ce5c42 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#14 0x00007fffa46fa165 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#15 0x00007fffa46fa200 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#16 0x00007fffa47291e8 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#17 0x00007fffa47396e7 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#18 0x00007fffa46e7437 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#19 0x00007fffa4dad689 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#20 0x00005555556b099e in ?? ()
#21 0x00005555556a74ab in _PyObject_MakeTpCall ()
#22 0x00005555556bf060 in ?? ()
#23 0x00005555556bb4b7 in ?? ()
#24 0x00005555556a785b in ?? ()
#25 0x00007fffa4d9af93 in ?? () from /home/aaron/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so
#26 0x00005555556a74ab in _PyObject_MakeTpCall ()
#27 0x000055555569fe66 in _PyEval_EvalFrameDefault ()
#28 0x00005555556b11ec in _PyFunction_Vectorcall ()
#29 0x00005555556998cb in _PyEval_EvalFrameDefault ()
#30 0x00005555556a6634 in _PyObject_FastCallDictTstate ()
#31 0x00005555556bae94 in ?? ()
#32 0x00005555556a744c in _PyObject_MakeTpCall ()
#33 0x000055555569fe66 in _PyEval_EvalFrameDefault ()
#34 0x0000555555695ed6 in ?? ()
#35 0x000055555578c366 in PyEval_EvalCode ()
#36 0x00005555557b9108 in ?? ()
#37 0x00005555557b1f5b in ?? ()
#38 0x00005555557b8e55 in ?? ()
#39 0x00005555557b8338 in _PyRun_SimpleFileObject ()
#40 0x00005555557b8033 in _PyRun_AnyFileObject ()
#41 0x00005555557a92de in Py_RunMain ()
#42 0x000055555577f32d in Py_BytesMain ()
#43 0x00007ffff7c78d90 in __libc_start_call_main (main=main@entry=0x55555577f2f0, argc=argc@entry=3, argv=argv@entry=0x7fffffffe3a8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#44 0x00007ffff7c78e40 in __libc_start_main_impl (main=0x55555577f2f0, argc=3, argv=0x7fffffffe3a8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe398) at ../csu/libc-start.c:392
#45 0x000055555577f225 in _start ()
```

I need to get a debug version of the pybind library for ORT, but I'm pretty sure the issue is coming from that layer and not ORT core.

**Comment by abock** [comment]
Also note I can reduce the Python test to the following and the segfault remains for both models:

```python
import onnxruntime
import sys
onnxruntime.InferenceSession(sys.argv[1])
```

**Comment by titaiwangms** [comment]
Fixed in ORT-nightly

**Comment by BowenBao** [comment]
^ as well as in pytorch CI?
