### ISSUE TITLE
Ability to partially trace and partially script the function

### ISSUE THREAD

**Issue by baijumeswani** [microsoft/onnx-script#556]
I am creating a utility that allows users to build a loss function.

I am considering using onnx-script for this purpose, but am having a hard time with trying to create an op.

```py
def create_mse_loss(reduction="mean"):
    # reduction can be mean, sum
    # loss = reduce((x-y)^2)
    @script()
    def MSELoss(output, target):
        nonlocal reduction # trace this part
        reduce_op = op.ReduceMean if reduction == "mean" else op.ReduceSum # trace this part
        return reduce_op((output - target)**2, axes=[0], keepdims=0) # script this part
    return MSELoss.to_model_proto()

onnx.save(create_mse_loss("sum"), "mseloss.onnx")
```

error I get:
```
Traceback (most recent call last):
  File "__________________________", line 31, in <module>
    onnx.save(create_mse_loss("sum"), "mseloss.onnx")
  File "__________________________", line 20, in create_mse_loss
    def MSELoss(output, target):
  File "/home/bmeswani/github/onnx-script/onnxscript/main.py", line 108, in transform
    result = script_check(ast, opset, env, src, default_opset=default_opset)
  File "/home/bmeswani/github/onnx-script/onnxscript/main.py", line 53, in script_check
    return convert.top_level_stmt(f)
  File "/home/bmeswani/github/onnx-script/onnxscript/converter.py", line 1365, in top_level_stmt
    analysis.do_liveness_analysis(stmt, self.message)
  File "/home/bmeswani/github/onnx-script/onnxscript/analysis.py", line 154, in do_liveness_analysis
    live = visit(s, live)
  File "/home/bmeswani/github/onnx-script/onnxscript/analysis.py", line 98, in visit
    live = do_visit(stmt, live_out)
  File "/home/bmeswani/github/onnx-script/onnxscript/analysis.py", line 149, in do_visit
    raise ValueError(formatter(stmt, f"Unsupported statement type {type(stmt)!r}."))
  File "/home/bmeswani/github/onnx-script/onnxscript/converter.py", line 236, in message
    return self.source_of(node).msg(error_msg)
  File "/home/bmeswani/github/onnx-script/onnxscript/converter.py", line 232, in source_of
    return sourceinfo.SourceInfo(node, self.source, self.current_fn.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

Other than defining two different functions and scripting them and other than having a branch in my onnx model, is there a way I can achieve this?

**Comment by baijumeswani** [comment]
@justinchuby helped me with this. Although it is not quite what I want, I can make do with this for now.
